### PR TITLE
check if have empty kwargs

### PR DESCRIPTION
**Pull request by isaacsas**
Fixes https://github.com/SciML/DiffEqBase.jl/issues/750

### CODE REVIEW

**Review by ChrisRackauckas — APPROVED** [review]

**Comment by isaacsas** [comment]
Probably would be good to make a bug fix release if/when this gets merged as this is likely a pretty confusing error to some users.

**Comment by isaacsas** [comment]
Sure

**Comment by ChrisRackauckas** [comment]
yeah it'll be a quick patch.

**Comment by isaacsas** [comment]
Strangely I'm not able to get the error when I directly build a `f(du,u,p,t)` or `f(u,p,t)`. In this case I guess a kwarg gets passed?

**Comment by isaacsas** [comment]
Ahh, I must have tested on the wrong version as it seems like the issue is actually from ModelingToolkit which is forwarding an invalid kwarg:
```
keys(kwargs) = (:check_length,)
```

I'll move this over to ModelingToolkit.

**Pull request closed without merging**
