### PR TITLE
Use TriangularSolve.jl for the ldiv!

### PR DESCRIPTION
**Pull request by ChrisRackauckas**
@yingboma @chriselrod is this a good idea?

### CODE REVIEW

**Comment by YingboMa** [comment]
Less I am missing something, this PR doesn't seem to change anything. `import` doesn't bring anything to the scope except the module name.

**Comment by chriselrod** [comment]
`TriangularSolve.jl` also only currently supports 2/4 `trsm!` permutations.
Which permutations are used here?

**Comment by YingboMa** [comment]
I think the only `ldiv!` usage here is `trsv!`

**Comment by chriselrod** [comment]
> I think the only `ldiv!` usage here is `trsv!`, so there is probably not much improvement.

I haven't implemented `trsv!` in TriangularSolve.jl.

**Pull request closed without merging**
