### PR TITLE
Add  NonlinearLeastSquaresProblem dispatches

### PR DESCRIPTION
**Pull request by avik-pal**
Needs to wait on https://github.com/SciML/SciMLBase.jl/pull/500

### CODE REVIEW

**Review by ChrisRackauckas — APPROVED** [review]

**Comment by ChrisRackauckas** [comment]
Is this close to done?

**Comment by avik-pal** [comment]
Let's wait and get all of the 3 NLS PRs in together?

**Comment by ChrisRackauckas** [comment]
Yes, I just wasn't sure what the current state is. I thought the NonlinearSolve part was done?

**Comment by avik-pal** [comment]
I just need to cross-verify certain parts from other implementations and create a MWE for the linear solve aliasing thing I mentioned

**Pull request merged**
