### PR TITLE
IncrementingODEProblem and IncrementingODEFunction

### PR DESCRIPTION
**Pull request by kanav99**
This is the bare minimum we need for incrementing forms, we can discuss what all things might make sense.

### CODE REVIEW

**Comment by kanav99** [comment]
Idea: We can add conversions to and from standard ODE problem using Williamson wrappers

**Comment by kanav99** [comment]
Updated to support kwargs, now we can do scaling like suggested by Simon, I think this is good to merge, unless we need to convert them to args instead of kwargs

**Comment by ChrisRackauckas** [comment]
Let's let @simonbyrne take a look. If it matches what they need, then we can do our merging brigade.

**Comment by simonbyrne** [comment]
Can you expand a bit on how these would work? How would a user interact with them?

**Comment by kanav99** [comment]
You can see this comment https://github.com/SciML/OrdinaryDiffEq.jl/pull/1185#issuecomment-650531272 it shows how a user can define a `f` for the problem

**Comment by simonbyrne** [comment]
How are they related? i.e. when do I use IncrementingODEFunction vs IncrementingODEProblem?

**Comment by ChrisRackauckas** [comment]
It might make sense to just have IncrementingODEFunction. IncrementingODEProblem is just a shorthand where you give it `f` and it builds an ODEProblem with an IncrementingODEFunction, but I'm not sure it's necessary. SecondOrderODEProblem and such are a bit different from this because they require different inputs and for example make an ArrayPartition to put together initial conditions, but IncrementingODEProblem just passes all of the arguments forward so it doesn't do all that much.

**Comment by simonbyrne** [comment]
> It might make sense to just have IncrementingODEFunction.

That makes sense, I'll try that with the CliMA solvers.

**Comment by simonbyrne** [comment]
Would be good to document the interface: see my comments here:  https://github.com/SciML/OrdinaryDiffEq.jl/pull/1185#issuecomment-650894826

**Comment by kanav99** [comment]
Yes IncrementingODEProblem won't be needed, but it is a convenient constructor for getting directly f -> prob, so I would really like it to stay (lol, between my two comments, GitHub went down)

**Comment by ChrisRackauckas** [comment]
It does match the others, so it is consistent. And we always document by problem. So I don't see any harm in it, though it's interesting that it's not entirely necessary.

**Comment by devmotion** [comment]
Would it make sense to just define the convenient constructor but not make it a separate type?

**Comment by ChrisRackauckas** [comment]
Yes, that's what we do with the others. There's also a trait that is set in the ODEProblem so you could know how it was constructed, though that has largely been supersceded now by using the DiffEqFunction types. So, no need for another problem type (though you build a fake one to use the "inner constructor")

**Comment by simonbyrne** [comment]
I think it would make sense to define an additional abstract type in between, i.e.
```julia
abstract type AbstractIncrementingODEFunction <: AbstractODEFunction{true}
end
```
so that users could subtype that directly rather than use a wrapper, and then just define

```julia
const IncrementingODEProblem{uType,tType,P,F<: AbstractIncrementingODEFunction,K,PT} = ODEProblem{uType,tType,true,P,F,K,PT}
```

**Comment by simonbyrne** [comment]
to be more specific, the following seems to work pretty well:
```julia
abstract type AbstractIncrementingODEFunction <: DiffEqBase.AbstractODEFunction{true}
end
struct IncrementingODEFunction{F} <: AbstractIncrementingODEFunction
    f::F
end

const IncrementingODEProblem{uType,tType,P,F<: AbstractIncrementingODEFunction,K,PT} =
    ODEProblem{uType,tType,true,P,F,K,PT}

IncrementingODEProblem(f::AbstractIncrementingODEFunction, args...; kwargs...) = 
    ODEProblem(f, args...; kwargs...)

IncrementingODEProblem(f, args...; kwargs...) =
    ODEProblem(IncrementingODEFunction(f), args...; kwargs...)
```

**Comment by simonbyrne** [comment]
Or could we make it an alternative value for the `iip` parameter? Though I imagine there are a lot of places which assume it is a `Bool`.

**Comment by ChrisRackauckas** [comment]
A lot of places assume it's a bool. I think it would be very breaking to change it. Though, IncrementingODEFunction would always be in-place, so I think it doesn't need it, so in theory we could equate `:incrementing` with `true` but... I can see this being really breaking in weird ways.

**Comment by simonbyrne** [comment]
Perhaps just consider it a request for your next rewrite 😄

**Comment by ChrisRackauckas** [comment]
So are we doing this?

**Comment by kanav99** [comment]
Yes, it's ready to merge according to me!

**Pull request merged**
