### PR TITLE
Implement Stalling and Use ReturnCode

### PR DESCRIPTION
**Pull request by avik-pal**
- [x] Stalling
- [x] Provide a deprecation path and use new return codes from SciMLBase
- [x] Needs https://github.com/SciML/SciMLBase.jl/pull/587
- [x] Wait for https://github.com/SciML/NonlinearSolve.jl/pull/345 tests to pass

### CODE REVIEW

**Comment by avik-pal** [comment]
Good to go once the SciMLBase PR is merged

**Comment by avik-pal** [comment]
I dont think the failure is related to this change, but I also don't see any tests failing on master

**Comment by ChrisRackauckas** [comment]
@AayushSabharwal https://github.com/SciML/DiffEqBase.jl/actions/runs/7518913080/job/20466812449?pr=994#step:6:1255

**Review by ChrisRackauckas — APPROVED** [review]

**Comment by AayushSabharwal** [comment]
https://github.com/SciML/RecursiveArrayTools.jl/pull/333

**Pull request merged**
