### PR TITLE
Fast no broadcast

### PR DESCRIPTION
**Pull request by chriselrod**
Should hopefully improve latency by reducing the amount of compiled code. In theory, should also improve runtime performance by a negligible amount due to removing a branch and reducing code size.

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Isn't that the default?

And OrdinaryDiffEq would have a lot more of these.

**Comment by chriselrod** [comment]
> Isn't that the default?
> 
> And OrdinaryDiffEq would have a lot more of these.

It's the default in 2.0, but not 1.
I figured we may as well keep support for 1 and specify `broadcast=false`.

**Comment by chriselrod** [comment]
OrdinaryDiffEq seems to already be setting `broadcast=false` everywhere, but may as well bump the compat to allow v0.2 support.

**Review by YingboMa — APPROVED** [review]

**Comment by chriselrod** [comment]
OrdinaryDiffEq does not explicitly depend on FastBroadcast, so no need to change anything there:
https://github.com/SciML/OrdinaryDiffEq.jl/blob/83c16d1864ad7a51f7111d72585475a4a8b3ed09/src/OrdinaryDiffEq.jl#L58

**Pull request merged**
