### PR TITLE
Check pointer not values when deciding whether to remake

### PR DESCRIPTION
**Pull request by ChrisRackauckas**
Fixes https://github.com/SciML/DifferentialEquations.jl/issues/620

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
@christopher-dG would you happen to know why this doesn't seem to be triggering the GPU tests?

**Comment by christopher-dG** [comment]
Sorry I wasn't in time for this. [It looks like they did run](https://gitlab.com/JuliaGPU/DiffEqBase.jl/-/jobs/594625216), so I'm guessing it wasn't showing up as a "status check" of this PR?

**Comment by ChrisRackauckas** [comment]
Yeah, it didn't show up as a status check. That's curious.

**Comment by christopher-dG** [comment]
My guess is that the token I used to set it up no longer has permissions to update commit statuses now that I don't have push access to these repos anymore.

**Comment by ChrisRackauckas** [comment]
Oh... I'll just give you access to those repos then. Need to find that whole list again.

**Comment by ChrisRackauckas** [comment]
You should have the right access through @SciML/gpu now

**Comment by christopher-dG** [comment]
Cool, next time a PR pops up on one of those repos we can see if it's working.

**Pull request merged**
