### PR TITLE
Generalizing NaN check for sparse matrices ...

### PR DESCRIPTION
**Pull request by goerch**
... and adding tests

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
It only seems to have fixed some downstream tests haha, nice.

**Comment by rory-humphries** [comment]
Release [v6.81.4](https://github.com/SciML/DiffEqBase.jl/releases/tag/v6.81.4) says this was merged (I assume that implies into main). However, it doesn't look like it was.

**Comment by ChrisRackauckas** [comment]
Interesting. I don't know what happened here.

**Comment by ChrisRackauckas** [comment]
https://github.com/SciML/DiffEqBase.jl/pull/741

**Pull request merged**
