### PR TITLE
Even more ForwardDiff dual detection robustness

### PR DESCRIPTION
**Pull request by ChrisRackauckas**
Fixes https://github.com/SciML/DiffEqBase.jl/issues/776 and fixes https://github.com/SciML/DiffEqBase.jl/issues/779

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
@ranocha this covers every case I can think of with just falling back to not converting when it cannot find a Dual type, and that fallback is always inferred (since the isempty case does eltype so when inference is failing it will still return the same type and so it should just infer fine. It will lose inference if it can find a dual though as that then would not match the eltype in some cases). Let me know after this patch is out whether there's anything still noticeable downstream. The tests cover a ton of cases here and every mapreduce catches the isempty case so it should be at least safe and robust (there there are probably a few ways to sneak a dual in, but this should catch 99.99% of the cases where someone is auto-diffing).

I can make the opt-out as well, but as the opt-out would make code unsafe for cases like autodiff (so i.e. make someone have to think more when using say Turing.jl), I'd hope the opt-out is rarely ever used.

**Comment by ranocha** [comment]
Thanks a lot! Sure, I will test it with Trixi.jl when it's merged and released. Maybe we're just extreme users - we pass our whole semidiscretization as parameters to the right-hand side, including meshes, buffers etc.

**Comment by ChrisRackauckas** [comment]
Okay cool, I think I handled all of the cases. There's a bunch of tests including structs with undefs, vectors with undefs, sets with structs with undefs, etc. There are a few cases where nesting an undef deep inside of there makes it not catch that there's a ForwardDiff, but this will make it just fallback to the previous behavior (of not catching the ForwardDiff Dual in that case and thus fail to automatically promote), so it shouldn't be "bad" and should be robust to not dying for heavily nested parameter structs. I think the real test will be releasing this as a patch and having @ranocha and @charleskawczynski rerun tests.

Sorry about this. I've been to clamp down on the set of "manual" behaviors and throwing a lot better error messages recently. If anything else got clamped that is usable behavior, just let me know.

**Comment by ranocha** [comment]
Sure, I will do that. Thanks for the quick fix! I will come back to you later when a new version is released.

**Comment by charleskawczynski** [comment]
Looks like this fixed it for us, thanks!

**Comment by ranocha** [comment]
Looks like this fixed it for us, too - or at least it's hidden by other [CI failures using Julia v1.8](https://github.com/trixi-framework/Trixi.jl/pull/1074)...

**Pull request merged**
