### PR TITLE
Change to NonlinearSolve.jl

### PR DESCRIPTION
**Pull request by kanav99**
@YingboMa @ChrisRackauckas

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
What makes this WIP?

**Comment by kanav99** [comment]
Because it still doesn't pass `integrator.u` as a parameter to the `zero_func`. I passed this to test the `ad_tests.jl` file

**Comment by ChrisRackauckas** [comment]
Can we just dispatch to Regula Falsi on duals for now, merge, and then handle the other problem?

**Comment by kanav99** [comment]
The problem with Falsi is that - for linear condition functions, it finds the solution in one iteration. But it is a very high probability that the solution it finds is slightly greater and keeps on setting the `right` value, `left` goes on unchanged.

**Comment by ChrisRackauckas** [comment]
But that's no worse than before, just no better in the AD case?

**Comment by kanav99** [comment]
Let's wait for tests to pass, especially downstream

**Comment by ChrisRackauckas** [comment]
We need to switch to github actions

**Comment by kanav99** [comment]
I have rebased and all the tests pass. This can be merged while I bring Falsi in a separate PR.

**Pull request merged**
