### PR TITLE
Fix splitthreads trajectory choices and test it better

### PR DESCRIPTION
**Pull request by ChrisRackauckas**
Fixes https://github.com/SciML/DiffEqBase.jl/issues/495 and fixes https://github.com/SciML/DiffEqBase.jl/issues/494

### CODE REVIEW

**Comment by MFairley** [comment]
@ChrisRackauckas thanks so much for making these fixes so quickly. I think EnsembleSplitThreads might broken now. I'm getting this error

```
julia> include("test/ensemble_mem_test.jl")
ERROR: LoadError: UndefRefError: access to undefined reference
Stacktrace:
 [1] getindex at ./array.jl:788 [inlined]
 [2] iterate at ./array.jl:764 [inlined] (repeats 2 times)
 [3] vector_batch_data_to_arr(::Array{Array{Any,1},1}) at /Users/mfairley/.julia/packages/DiffEqBase/BZxEO/src/ensemble/basic_ensemble_solve.jl:249
 [4] solve_batch(::EnsembleProblem{ODEProblem{Array{Float64,1},Tuple{Float64,Float64},true,Array{Array{Float64,1},1},ODEFunction{true,typeof(lorenz!),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}},DiffEqBase.StandardODEProblem},typeof(prob_func),typeof(DiffEqBase.DEFAULT_OUTPUT_FUNC),typeof(DiffEqBase.DEFAULT_REDUCTION),Array{Any,1}}, ::Tsit5, ::EnsembleSplitThreads, ::UnitRange{Int64}, ::Int64) at /Users/mfairley/.julia/packages/DiffEqBase/BZxEO/src/ensemble/basic_ensemble_solve.jl:205
 [5] macro expansion at /Users/mfairley/.julia/packages/DiffEqBase/BZxEO/src/ensemble/basic_ensemble_solve.jl:95 [inlined]
 [6] macro expansion at ./util.jl:234 [inlined]
 [7] __solve(::EnsembleProblem{ODEProblem{Array{Float64,1},Tuple{Float64,Float64},true,Array{Array{Float64,1},1},ODEFunction{true,typeof(lorenz!),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}},DiffEqBase.StandardODEProblem},typeof(prob_func),typeof(DiffEqBase.DEFAULT_OUTPUT_FUNC),typeof(DiffEqBase.DEFAULT_REDUCTION),Array{Any,1}}, ::Tsit5, ::EnsembleSplitThreads; trajectories::Int64, batch_size::Int64, pmap_batch_size::Int64, kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /Users/mfairley/.julia/packages/DiffEqBase/BZxEO/src/ensemble/basic_ensemble_solve.jl:89
 [8] #solve#445 at /Users/mfairley/.julia/packages/DiffEqBase/BZxEO/src/solve.jl:80 [inlined]
 [9] ##core#291() at /Users/mfairley/.julia/packages/BenchmarkTools/eCEpo/src/execution.jl:371
 [10] ##sample#292(::BenchmarkTools.Parameters) at /Users/mfairley/.julia/packages/BenchmarkTools/eCEpo/src/execution.jl:377
 [11] _run(::BenchmarkTools.Benchmark{Symbol("##benchmark#290")}, ::BenchmarkTools.Parameters; verbose::Bool, pad::String, kwargs::Base.Iterators.Pairs{Symbol,Integer,NTuple{4,Symbol},NamedTuple{(:samples, :evals, :gctrial, :gcsample),Tuple{Int64,Int64,Bool,Bool}}}) at /Users/mfairley/.julia/packages/BenchmarkTools/eCEpo/src/execution.jl:405
 [12] (::Base.var"#inner#2"{Base.Iterators.Pairs{Symbol,Integer,NTuple{5,Symbol},NamedTuple{(:verbose, :samples, :evals, :gctrial, :gcsample),Tuple{Bool,Int64,Int64,Bool,Bool}}},typeof(BenchmarkTools._run),Tuple{BenchmarkTools.Benchmark{Symbol("##benchmark#290")},BenchmarkTools.Parameters}})() at ./essentials.jl:715
 [13] #invokelatest#1 at ./essentials.jl:716 [inlined]
 [14] #run_result#37 at /Users/mfairley/.julia/packages/BenchmarkTools/eCEpo/src/execution.jl:32 [inlined]
 [15] run(::BenchmarkTools.Benchmark{Symbol("##benchmark#290")}, ::BenchmarkTools.Parameters; progressid::Nothing, nleaves::Float64, ndone::Float64, kwargs::Base.Iterators.Pairs{Symbol,Integer,NTuple{5,Symbol},NamedTuple{(:verbose, :samples, :evals, :gctrial, :gcsample),Tuple{Bool,Int64,Int64,Bool,Bool}}}) at /Users/mfairley/.julia/packages/BenchmarkTools/eCEpo/src/execution.jl:94
 [16] #warmup#45 at /Users/mfairley/.julia/packages/BenchmarkTools/eCEpo/src/execution.jl:141 [inlined]
 [17] warmup(::BenchmarkTools.Benchmark{Symbol("##benchmark#290")}) at /Users/mfairley/.julia/packages/BenchmarkTools/eCEpo/src/execution.jl:141
 [18] top-level scope at /Users/mfairley/.julia/packages/BenchmarkTools/eCEpo/src/execution.jl:287
 [19] include(::String) at ./client.jl:439
 [20] top-level scope at REPL[1]:1
 [21] eval(::Module, ::Any) at ./boot.jl:331
 [22] eval_user_input(::Any, ::REPL.REPLBackend) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/REPL/src/REPL.jl:86
 [23] run_backend(::REPL.REPLBackend) at /Users/mfairley/.julia/packages/Revise/WkyNB/src/Revise.jl:1023
 [24] top-level scope at none:0
 [25] eval(::Module, ::Any) at ./boot.jl:331
 [26] eval_user_input(::Any, ::REPL.REPLBackend) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/REPL/src/REPL.jl:86
 [27] run_backend(::REPL.REPLBackend) at /Users/mfairley/.julia/packages/Revise/WkyNB/src/Revise.jl:1023
 [28] top-level scope at none:0
in expression starting at /Users/mfairley/Projects/OUDCEAMarkov/test/ensemble_mem_test.jl:35
```

running this script

```
using Distributed
@everywhere using DifferentialEquations
using Profile
using StaticArrays
using BenchmarkTools

@everywhere function lorenz(u,p,t)
    du = similar(u)
    du[1] = 10.0*(u[2]-u[1])
    du[2] = u[1]*(28.0-u[3]) - u[2]
    du[3] = u[1]*u[2] - (8/3)*u[3]
    return du
end

@everywhere function lorenz!(du,u,p,t)
    du[1] = 10.0*(u[2]-u[1])
    du[2] = u[1]*(28.0-u[3]) - u[2]
    du[3] = u[1]*u[2] - (8/3)*u[3]
end

# u0 = SVector{3, Float64}([1.0, 0.0, 0.0])
u0 = [1.0, 0.0, 0.0]
tspan = (0.0, 100.0)
p = [1, 2.0, 3]
p= [rand(3) for i = 1:100]
prob = ODEProblem(lorenz!, u0, tspan, p)

@everywhere function prob_func(prob,i,repeat)
    prob = remake(prob, tspan=(rand(), 100.0), p=p[i])
    return prob
end

ensemble_prob = EnsembleProblem(prob, prob_func = prob_func, safetycopy=true)

@benchmark sim = solve(ensemble_prob, Tsit5(), EnsembleSplitThreads(), trajectories=100)
```

**Comment by ChrisRackauckas** [comment]
`@everywhere p= [rand(3) for i = 1:100]`

**Comment by MFairley** [comment]
My mistake but the error with EnsembleSplitThreads still stands. Here's a better MWE.

```
using Distributed
@everywhere using DifferentialEquations
using Profile
using BenchmarkTools

@everywhere function lorenz!(du,u,p,t)
    du[1] = 10.0*(u[2]-u[1])
    du[2] = u[1]*(28.0-u[3]) - u[2]
    du[3] = u[1]*u[2] - (8/3)*u[3]
end

u0 = [1.0, 0.0, 0.0]
tspan = (0.0, 100.0)
p = [1, 2.0, 3]
prob = ODEProblem(lorenz!, u0, tspan, p)

@everywhere function prob_func(prob,i,repeat)
    prob = remake(prob, tspan=(rand(), 100.0), p=rand(3))
    return prob
end

ensemble_prob = EnsembleProblem(prob, prob_func = prob_func, safetycopy=true)

println("Running EnsembleSerial()")
solve(ensemble_prob, Tsit5(), EnsembleSerial(), trajectories=100)
println("Running EnsembleThreads()")
solve(ensemble_prob, Tsit5(), EnsembleThreads(), trajectories=100)
println("Running EnsembleDistributed()")
solve(ensemble_prob, Tsit5(), EnsembleDistributed(), trajectories=100)
println("Running EnsembleSplitThreads()")
solve(ensemble_prob, Tsit5(), EnsembleSplitThreads(), trajectories=100)
```

```
julia> include("test/ensemble_mem_test.jl")
Running EnsembleSerial()
Running EnsembleThreads()
Running EnsembleDistributed()
Running EnsembleSplitThreads()
ERROR: LoadError: UndefRefError: access to undefined reference
Stacktrace:
 [1] getindex at ./array.jl:788 [inlined]
 [2] iterate at ./array.jl:764 [inlined] (repeats 2 times)
 [3] vector_batch_data_to_arr(::Array{Array{Any,1},1}) at /Users/mfairley/.julia/packages/DiffEqBase/BZxEO/src/ensemble/basic_ensemble_solve.jl:249
 [4] solve_batch(::EnsembleProblem{ODEProblem{Array{Float64,1},Tuple{Float64,Float64},true,Array{Float64,1},ODEFunction{true,typeof(lorenz!),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}},DiffEqBase.StandardODEProblem},typeof(prob_func),typeof(DiffEqBase.DEFAULT_OUTPUT_FUNC),typeof(DiffEqBase.DEFAULT_REDUCTION),Array{Any,1}}, ::Tsit5, ::EnsembleSplitThreads, ::UnitRange{Int64}, ::Int64) at /Users/mfairley/.julia/packages/DiffEqBase/BZxEO/src/ensemble/basic_ensemble_solve.jl:205
 [5] macro expansion at /Users/mfairley/.julia/packages/DiffEqBase/BZxEO/src/ensemble/basic_ensemble_solve.jl:95 [inlined]
 [6] macro expansion at ./util.jl:234 [inlined]
 [7] __solve(::EnsembleProblem{ODEProblem{Array{Float64,1},Tuple{Float64,Float64},true,Array{Float64,1},ODEFunction{true,typeof(lorenz!),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}},DiffEqBase.StandardODEProblem},typeof(prob_func),typeof(DiffEqBase.DEFAULT_OUTPUT_FUNC),typeof(DiffEqBase.DEFAULT_REDUCTION),Array{Any,1}}, ::Tsit5, ::EnsembleSplitThreads; trajectories::Int64, batch_size::Int64, pmap_batch_size::Int64, kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /Users/mfairley/.julia/packages/DiffEqBase/BZxEO/src/ensemble/basic_ensemble_solve.jl:89
 [8] #solve#445 at /Users/mfairley/.julia/packages/DiffEqBase/BZxEO/src/solve.jl:80 [inlined]
 [9] top-level scope at /Users/mfairley/Projects/OUDCEAMarkov/test/ensemble_mem_test.jl:32
 [10] include(::String) at ./client.jl:439
 [11] top-level scope at REPL[2]:1
 [12] eval(::Module, ::Any) at ./boot.jl:331
 [13] eval_user_input(::Any, ::REPL.REPLBackend) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/REPL/src/REPL.jl:86
 [14] run_backend(::REPL.REPLBackend) at /Users/mfairley/.julia/packages/Revise/WkyNB/src/Revise.jl:1023
 [15] top-level scope at none:0
 [16] eval(::Module, ::Any) at ./boot.jl:331
 [17] eval_user_input(::Any, ::REPL.REPLBackend) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/REPL/src/REPL.jl:86
 [18] run_backend(::REPL.REPLBackend) at /Users/mfairley/.julia/packages/Revise/WkyNB/src/Revise.jl:1023
 [19] top-level scope at none:0
in expression starting at /Users/mfairley/Projects/OUDCEAMarkov/test/ensemble_mem_test.jl:32
```

**Comment by ChrisRackauckas** [comment]
oh, that had a thread-safety issue. Fixed in https://github.com/SciML/DiffEqBase.jl/pull/501 . Now we should be good.

**Pull request merged**
