### PR TITLE
switch diffeqoperators to scimloperators

### PR DESCRIPTION
**Pull request by vpuri3**
plan: https://github.com/SciML/SciMLOperators.jl/issues/142

In `test/basic_operator_tests.jl, test/affine_operator_tests.jl`, there are tests for DiffEqOperators. Let's leave that as it is till DiffEqOps are remove from downstream packages.

### CODE REVIEW

**Review by ChrisRackauckas — APPROVED** [review]

**Comment by vpuri3** [comment]
will rerun CI once downstream PRs are merged. maybe we get some more issues.

**Comment by vpuri3** [comment]
rerunning CI

**Comment by ChrisRackauckas** [comment]
Don't you want to wait for https://github.com/JuliaRegistries/General/pull/77143 ?

**Comment by vpuri3** [comment]
haha yes. i was just playing to see how long it would take before GH picks up the merge.

**Comment by ChrisRackauckas** [comment]
https://github.com/SciML/DiffEqBase.jl/actions/runs/4108922303/jobs/7090163844#step:6:1143

Looks like DiffEqOperators needs to be setup for backwards compatibility first.

**Comment by vpuri3** [comment]
Yes - glad we're catching all the downstream packages that need to be updated

**Comment by vpuri3** [comment]
Weird, it's still picking up the old version of Sundials with DiffEqOperators.

**Comment by vpuri3** [comment]
same delaydiffeq failing here due to accuracy. rerunning

**Pull request merged**
