### PR TITLE
RFC: Add nlsolve default

### PR DESCRIPTION
**Pull request by YingboMa**
This is breaking. How should we go about this? @ChrisRackauckas

### CODE REVIEW

**Comment by devmotion** [comment]
A bit unfortunate that Setfield does not support updating multiple fields at a time (https://github.com/jw3126/Setfield.jl/issues/62 mentions Kaleido.jl but it seems it only provides batch lenses but no equivalent to `@set!`). Maybe it doesn't have any impact on performance and e.g. the compiler is smart enough and removes intermediate constructions of `NLFunctional` etc. instances?

**Comment by ChrisRackauckas** [comment]
Let's do it, but not today. Let's get the controller downstream fixes all green first, then make the next move.

**Comment by ChrisRackauckas** [comment]
Also, let's make sure that any changes here make sense considering what will happen to linear solvers.

**Comment by YingboMa** [comment]
If we are gonna make a breaking change, maybe we should change `max_iter` to `maxiters` to be consistant?

> Maybe it doesn't have any impact on performance and e.g. the compiler is smart enough and removes intermediate constructions of NLFunctional etc. instances?

Yes, Julia is smart enough to not construct and destruct the struct multiple times.
```julia
julia> @code_typed debuginfo=:none DiffEqBase.handle_defaults(1, NLNewton(κ=0.1, fast_convergence_cutoff=0.2, new_W_dt_cutoff=0.2))
CodeInfo(
1 ── %1  = Base.getfield(nlalg@_3, :κ)::Float64
│    %2  = invoke Base.divgcd(1::Int64, 100::Int64)::Tuple{Int64, Int64}
│    %3  = Base.getfield(%2, 2)::Int64
│    %4  = Base.slt_int(%3, 0)::Bool
└───       goto #5 if not %4
2 ── %6  = Base.neg_int(%3)::Int64
│    %7  = Base.slt_int(%6, 0)::Bool
└───       goto #4 if not %7
3 ──       invoke Base.__throw_rational_argerror_typemin(Int64::Type)::Union{}
└───       unreachable
4 ──       nothing::Nothing
5 ┄─       goto #6
6 ──       goto #7
7 ──       goto #8
8 ──       goto #9
9 ──       goto #10
10 ─ %17 = Base.getfield(nlalg@_3, :fast_convergence_cutoff)::Float64
│    %18 = Base.getfield(nlalg@_3, :new_W_dt_cutoff)::Float64
│    %19 = invoke Base.divgcd(1::Int64, 5::Int64)::Tuple{Int64, Int64}
│    %20 = Base.getfield(%19, 2)::Int64
│    %21 = Base.slt_int(%20, 0)::Bool
└───       goto #14 if not %21
11 ─ %23 = Base.neg_int(%20)::Int64
│    %24 = Base.slt_int(%23, 0)::Bool
└───       goto #13 if not %24
12 ─       invoke Base.__throw_rational_argerror_typemin(Int64::Type)::Union{}
└───       unreachable
13 ─       nothing::Nothing
14 ┄       goto #15
15 ─       goto #16
16 ─       goto #17
17 ─       goto #18
18 ─       goto #19
19 ─ %34 = invoke Base.divgcd(1::Int64, 5::Int64)::Tuple{Int64, Int64}
│    %35 = Base.getfield(%34, 2)::Int64
│    %36 = Base.slt_int(%35, 0)::Bool
└───       goto #23 if not %36
20 ─ %38 = Base.neg_int(%35)::Int64
│    %39 = Base.slt_int(%38, 0)::Bool
└───       goto #22 if not %39
21 ─       invoke Base.__throw_rational_argerror_typemin(Int64::Type)::Union{}
└───       unreachable
22 ─       nothing::Nothing
23 ┄       goto #24
24 ─       goto #25
25 ─       goto #26
26 ─       goto #27
27 ─       goto #28
28 ─ %49 = %new(NLNewton{Float64, Int64, Float64, Float64}, %1, 10, %17, %18)::NLNewton{Float64, Int64, Float64, Float64}
└───       return %49
) => NLNewton{Float64, Int64, Float64, Float64}

julia>
```
Note that there's only one `NLNewton` constructor call.

**Comment by ChrisRackauckas** [comment]
>If we are gonna make a breaking change, maybe we should change max_iter to maxiters to be consistant?

Yes

**Pull request closed without merging**
