### PR TITLE
fix example of GeometricIntegratorsDiffEq

### PR DESCRIPTION
**Pull request by ranocha**
Before, the default example of https://github.com/SciML/GeometricIntegratorsDiffEq.jl returned an error
```
ERROR: UndefVarError: StandardODEProblem not defined
Stacktrace:
 [1] __solve(prob::ODEProblem{Vector{Float64}, Tuple{Float64, Float64}, true, SciMLBase.NullParameters, ODEFunction{true, typeof(lorenz), LinearAlgebra.UniformScaling{Bool}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, typeof(SciMLBase.DEFAULT_OBSERVED), Nothing}, Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}, SciMLBase.StandardODEProblem}, alg::GIEuler, timeseries::Vector{Any}, ts::Vector{Any}, ks::Vector{Any}; verbose::Bool, save_start::Bool, dt::Float64, timeseries_errors::Bool, callback::Nothing, alias_u0::Bool, kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ GeometricIntegratorsDiffEq ~/.julia/dev/GeometricIntegratorsDiffEq/src/solve.jl:62
 [2] #solve_call#56
   @ ~/.julia/packages/DiffEqBase/U3Zj7/src/solve.jl:61 [inlined]
 [3] solve_up(prob::ODEProblem{Vector{Float64}, Tuple{Float64, Float64}, true, SciMLBase.NullParameters, ODEFunction{true, typeof(lorenz), LinearAlgebra.UniformScaling{Bool}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, typeof(SciMLBase.DEFAULT_OBSERVED), Nothing}, Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}, SciMLBase.StandardODEProblem}, sensealg::Nothing, u0::Vector{Float64}, p::SciMLBase.NullParameters, args::GIEuler; kwargs::Base.Iterators.Pairs{Symbol, Float64, Tuple{Symbol}, NamedTuple{(:dt,), Tuple{Float64}}})
   @ DiffEqBase ~/.julia/packages/DiffEqBase/U3Zj7/src/solve.jl:82
 [4] #solve#57
   @ ~/.julia/packages/DiffEqBase/U3Zj7/src/solve.jl:70 [inlined]
 [5] top-level scope
   @ REPL[9]:1
```
This should get a new release as soon as possible. Then, GeometricIntegratorsDiffEq.jl should update the compat bound for DiffEqBase accordingly.

### CODE REVIEW

**Comment by ranocha** [comment]
The test failures are not related to this PR. They complain about `end` not being defined in https://github.com/SciML/OrdinaryDiffEq.jl/blob/3021916e201439166197f589b38d3a81949061ce/src/perform_step/explicit_rk_perform_step.jl#L96 I guess that's an issue with FastBroadcast?

**Comment by devmotion** [comment]
Same problem as https://github.com/SciML/OrdinaryDiffEq.jl/issues/1410, it seems.

**Comment by ChrisRackauckas** [comment]
@chriselrod mention here when tests should be re-ran.

**Comment by chriselrod** [comment]
Now. https://github.com/JuliaRegistries/General/pull/37189#event-4778977877

**Pull request merged**
