### PR TITLE
fix ODE_DEFAULT_NORM for empty vectors

### PR DESCRIPTION
**Pull request by oscardssmith**
fixes problem introduced in https://github.com/SciML/DiffEqBase.jl/pull/697.

### CODE REVIEW

**Review by ChrisRackauckas — APPROVED** [review]
why is the empty case important?

**Comment by oscardssmith** [comment]
the empty case matters because automatic simplification of problems (e.g. MTK) can sometimes manage to remove all variables from simple problems.

**Comment by ChrisRackauckas** [comment]
But it shouldn't even enter the solver in those cases, it should just bypass and build the solution?

**Comment by oscardssmith** [comment]
you certainly would think that, wouldn't you.

**Comment by ChrisRackauckas** [comment]
but... it does do that.

**Pull request merged**
