### PR TITLE
Using Falsi in rootfinding

### PR DESCRIPTION
**Pull request by kanav99**
Also adds the left or right option. Needs https://github.com/JuliaComputing/NonlinearSolve.jl/pull/18
@ChrisRackauckas 

Fixes https://github.com/SciML/DiffEqBase.jl/issues/564 https://github.com/SciML/DiffEqBase.jl/issues/553 and https://github.com/SciML/DiffEqBase.jl/issues/515

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Add what issues are closed by this to the first comment.

**Comment by kanav99** [comment]
Needs https://github.com/JuliaComputing/NonlinearSolve.jl/pull/20

**Comment by kanav99** [comment]
I cant get the downstream tests to use 0.3.0 for some reason

**Comment by ChrisRackauckas** [comment]
https://github.com/SciML/DiffEqBase.jl/pull/613/checks?check_run_id=1526461419#step:6:328

**Comment by ChrisRackauckas** [comment]
Looks like it's using the right package version.

**Pull request merged**
