### PR TITLE
Non-allocating isinplace

### PR DESCRIPTION
**Pull request by YingboMa**
PR:
```julia
julia> @ballocated NonlinearProblem((u,p)->u, 1.0)
0
```
Master:
```julia
julia> @ballocated NonlinearProblem((u,p)->u, 1.0)
5040
```

### CODE REVIEW

**Review by ChrisRackauckas — APPROVED** [review]

**Comment by YingboMa** [comment]
This PR moves the `isinplace` computation to compile time. It will break code that dynamically switches from out-of-place to in-place. But the advantage is that any code with static signatures will have zero-cost `isinplace` computation. @ChrisRackauckas

**Comment by ChrisRackauckas** [comment]
It's expected that changing the dispatches is not safe with this already, so making it non-allocating is good.

**Comment by kanav99** [comment]
I get this error on running downstream AD tests and reverting this PR makes the test pass -
```
➜  DiffEqBase git:(nlsolve) ✗ julia15 test/downstream/ad_tests.jl              
AD Test 1
AD Test 2
AD Test 3
ERROR: LoadError: UndefRefError: access to undefined reference
Stacktrace:
 [1] getproperty(::Type{T} where T, ::Symbol) at ./Base.jl:28
 [2] #s261#1 at /Users/kanav/.julia/dev/DiffEqBase/src/utils.jl:7 [inlined]
 [3] #s261#1(::Any, ::Any) at ./none:0
 [4] (::Core.GeneratedFunctionStub)(::Any, ::Vararg{Any,N} where N) at ./boot.jl:527
 [5] isinplace(::Function, ::Int64) at /Users/kanav/.julia/dev/DiffEqBase/src/utils.jl:43
 [6] ODEFunction(::Function; kwargs::Base.Iterators.Pairs{Symbol,Nothing,NTuple{10,Symbol},NamedTuple{(:analytic, :tgrad, :jac, :jvp, :vjp, :Wfact, :Wfact_t, :paramjac, :syms, :colorvec),NTuple{10,Nothing}}}) at /Users/kanav/.julia/dev/DiffEqBase/src/diffeqfunction.jl:394
 [7] convert(::Type{ODEFunction}, ::Function) at /Users/kanav/.julia/dev/DiffEqBase/src/diffeqfunction.jl:1086
 [8] ODEProblem(::Function, ::Array{Float64,1}, ::Tuple{Float64,Float64}, ::Array{Float64,1}; kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /Users/kanav/.julia/dev/DiffEqBase/src/problems/ode_problems.jl:76
 [9] ODEProblem(::Function, ::Array{Float64,1}, ::Tuple{Float64,Float64}, ::Array{Float64,1}) at /Users/kanav/.julia/dev/DiffEqBase/src/problems/ode_problems.jl:76
 [10] top-level scope at /Users/kanav/.julia/dev/DiffEqBase/test/downstream/ad_tests.jl:146
 [11] include(::Function, ::Module, ::String) at ./Base.jl:380
 [12] include(::Module, ::String) at ./Base.jl:368
 [13] exec_options(::Base.JLOptions) at ./client.jl:296
 [14] _start() at ./client.jl:506
in expression starting at /Users/kanav/.julia/dev/DiffEqBase/test/downstream/ad_tests.jl:136
```

**Comment by ChrisRackauckas** [comment]
Revert it. I didn't see that CI didn't run because Travis ran out of credits.

**Pull request merged**
